spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/accounting
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html
    disable-swagger-default-url: true
  customProps:
    title: Accounting API Documentation
    version: 1.0
    author:
      name: Sefa Tascan
      email: sefatascan@hotmail.com

application:
  transaction:
    limit: 200